export const achievements = [
  {
    id: "first-step",
    icon: "🌱",
    title: "First Step",
    description: "Write your first memory.",
    requirement: "1 memory",
  },
  {
    id: "getting-into-it",
    icon: "✍️",
    title: "Getting Into It",
    description: "Write 5 memories.",
    requirement: "5 memories",
  },
  {
    id: "story-keeper",
    icon: "📖",
    title: "Story Keeper",
    description: "Write 10 memories.",
    requirement: "10 memories",
  },
  {
    id: "picture-this",
    icon: "📸",
    title: "Picture This",
    description: "Save a memory with a photo.",
    requirement: "1 photo memory",
  },
  {
    id: "soundtrack-of-me",
    icon: "🎵",
    title: "Soundtrack of Me",
    description: "Add music to a memory.",
    requirement: "1 music memory",
  },
  {
    id: "been-there",
    icon: "📍",
    title: "Been There",
    description: "Save a memory with a location.",
    requirement: "1 location memory",
  },
  {
    id: "three-day-rhythm",
    icon: "🔥",
    title: "Three Day Rhythm",
    description: "Write for 3 consecutive days.",
    requirement: "3 day streak",
  },
  {
    id: "week-of-me",
    icon: "🔥",
    title: "Week of Me",
    description: "Write for 7 consecutive days.",
    requirement: "7 day streak",
  },
  {
    id: "century-of-moments",
    icon: "💯",
    title: "Century of Moments",
    description: "Reach 100 memories.",
    requirement: "100 memories",
  },
];